### ISSUE TITLE
消息模板用的那一个？

### ISSUE THREAD

**Issue by chaoge6468** [Ruomoe/DouYinWechatWeather#1]
消息模板用的那一个？

**Comment by Ruomoe** [comment]
你微信公众平台所创建的

**Comment by chaoge6468** [comment]
> 你的微信公众平台所创建的

审核时间是7~14天

**Comment by Ruomoe** [comment]
可以使用微信公众测试号 无需审核 扫码即上 (https://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=sandbox/login)

**Comment by chaoge6468** [comment]
weatherapiurl  天气是用的那个服务呀

**Comment by Ruomoe** [comment]
你需要替换成你自己的天气接口 我用的是一刻天气的(http://www.yiketianqi.com/) 
示例: (https://www.yiketianqi.com/free/day?appid=一刻天气的appid&appsecret=一刻天气的appsecret=1&city=获取的城市)

**Comment by Ruomoe** [comment]
更正一下示例不小心给错了 (https://www.yiketianqi.com/free/day?appid=一刻天气的appid&appsecret=一刻天气的appsecret&unescape=1&city=城市)

**Comment by chaoge6468** [comment]
已成功调用，谢谢
