### ISSUE TITLE
自己的公众号有条件限制吧？

### ISSUE THREAD

**Issue by eirms** [Ruomoe/DouYinWechatWeather#2]
如果是用自己的公众号，必须是认证的服务号吗，订阅号应该不行吧。

**Comment by Ruomoe** [comment]
具体不清楚 我写的时候使用的测试接口号 你可以试试 流程应该是一样的 只是接口地址不同 你需要把代码中的 url 和 postUrl 换成你公众号的接口地址 具体可以参考一下微信的开发文档。
